config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/new'
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to dashboards_new_path
    else
     flash.now[:danger] = 'Invalid email/passwordcombination'
     render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to dashboards_new_path 
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

# Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/new.html.erb
<body class="main-body">
            <div class="banner-area">
              <h2> welcome to farmer friendly and eco-friendly dairy</h2>
            </div>
            <div class="section" id="aboutus">
              <div class="products">
                <h3> Our Products</h3>
                 <img src="images/products.jpg" alt="image">
                 <br>
                 <p>we provide our customers a wide variety of dairy products from organic milk to butter and cheese</span><P>
                 <a href="#">Read More</a>
                </div>
                <div class="products">
                <h3>Our Aim </h3>
                 <img src="images/aim.jpg">
                 <br>
                 <p>To build a <span style="color:green">strong </span><span style="color:red">,healthy </span>and <span style="color:blue">nutritious</span> country by providing an employement to all small-scale farmers <P>
                 <a href="#">Read More</a>
                </div>
                <div class="products">
                <h3>Working</h3>
                 <img src="images/working.png" alt="image">
                 <br>
                 <p> let"s start<P>
                 <a href="#">Read More</a>
              </div>
            </div>
            <div class="foot">
                <footer>
                    <div class="foot-main">
                        <div class="foot1">
                            <h3 font> About us</h3>
                            <p>A dairy is a business enterprise established for the processing of animal milk.mostly from cows or buffaloes,for human consumption.</p>
                            <a href="#">read more</a>
                        </div>
                        <div class="foot2">
                            <h3>find us</h3>
                            <p>BANASHANKARI </P>
                            <p>NEAR BANASHANKARI TTMC</p>
                            <p>BANGALORE-560082</p>
                            <p>TELEPHONE:08518-232205</p>
                        </div>
                        <div class="foot3">
                            <h3>Contact us</h3>
                            <p>Subscribe to get our latest updates and offers.</p>
                            <br>
                            <form class="" action="" method="POST">
                            <input type="email" name="subscribe"  class="emailid" placeholder="Enter Your Email ID"/><button type="submit" onclick=href"www.gmail.com"><span class="maile">submit</span></button>
                            <p>***Don't worry, we wont spam you!</p>
                            </form>
                        </div>
                        <div class="foot4">
                            <h3>follow us</h3>
                            <ul>
                              <li><a href="https://www.instagram.com/?hl=en"><i class="fab fa-instagram-square"></i></a></li>
                              <li><a href="https://www.bing.com/search?q=facebook&form=ANNTH1&refig=57c3a643f07b4d528577f9477c526b74"><i class="fab fa-facebook-square"></i></i></a></li>
                              <li><a href="https://www.bing.com/search?q=twitter&cvid=df49de1cdf96439c8e1c74517c24caca&aqs=edge.0.0l7.4519j0j9&FORM=ANAB01&PC=DCTS"><i class="fab fa-twitter-square"></i></i></a></li>
                            </ul>
                        </div>
                    <//div>
            </div>

    </body>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails
    Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael
    Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Dairy Mangement System", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", "#" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method:"delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webdairy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count,
      "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on
Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a>
family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast
series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at
the
<a href="https://www.railstutorial.org/contact">contact
page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="https://www.railstutorial.org/help">Rails Tutorial
Help page</a>.
To get help on this sample app, see the
<a href="https://www.railstutorial.org/book"><em>Ruby on
Rails Tutorial</em>
book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Dairy Mangement System</h1>
  <h2>
    This is the home page for the Dairy Mangement System
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Create my account", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
<h1><%= @user.name %></h1>
</div>